$(function(){
		$('#dowebok').fullpage({
		sectionsColor: ["#fff","#fff","#fff","#fff"],
		scrollBar:true
		});
		new WOW().init();
		$(".ding").top({"speen":1000,"animate":"slide"})
		
		$(".weixin").mouseover(function(){
			$(".ma").css("display","block")
		}).mouseout(function(){
			$(".ma").css("display","none")
		})
		
		$(".a1").mouseover(function(){
			$(".h2").css("display","block")
			$(".xiaoxue").css("display","block")
			$(".h3").css("display","none")
			$(".chuzhong").css("display","none")
			$(".h4").css("display","none")
			$(".gaozhong").css("display","none")
			$(".h5").css("display","none")
			$(".chongci").css("display","none")
			$(".shu").css("display","none")
			$(".shuxue").css("display","none")
			$(".ying").css("display","none")
			$(".wuli").css("display","none")
			$(".yingyu").css("display","none")
			$(".hua").css("display","none")
			$(".gu").css("display","none")
			$(".gaoy").css("display","none")
			$(".gaow").css("display","none")
			$(".gaoh").css("display","none")
			$(".cj").css("display","none")
			$(".gk").css("display","none")
		})
		$(".a2").mouseover(function(){
			$(".h3").css("display","block")
			$(".chuzhong").css("display","block")
			$(".h2").css("display","none")
			$(".chongci").css("display","none")
			$(".xiaoxue").css("display","none")
			$(".h4").css("display","none")
			$(".h5").css("display","none")
			$(".gaozhong").css("display","none")
			$(".shu").css("display","none")
			$(".shuxue").css("display","none")
			$(".ying").css("display","none")
			$(".wuli").css("display","none")
			$(".yingyu").css("display","none")
			$(".hua").css("display","none")
			$(".gu").css("display","none")
			$(".gaoy").css("display","none")
			$(".gaow").css("display","none")
			$(".gaoh").css("display","none")
			$(".cj").css("display","none")		
			$(".gk").css("display","none")
		}).mouseout(function(){
			$(".h2").css("display","none")
			$(".xiaoxue").css("display","none")		
		})
		$(".a3").mouseover(function(){
			$(".h4").css("display","block")
			$(".gaozhong").css("display","block")
			$(".h2").css("display","none")
			$(".xiaoxue").css("display","none")
			$(".h3").css("display","none")
			$(".chuzhong").css("display","none")
			$(".h5").css("display","none")
			$(".chongci").css("display","none")
			$(".shu").css("display","none")
			$(".shuxue").css("display","none")
			$(".ying").css("display","none")
			$(".wuli").css("display","none")
			$(".yingyu").css("display","none")
			$(".hua").css("display","none")
			$(".gu").css("display","none")
			$(".gaoy").css("display","none")
			$(".gaow").css("display","none")
			$(".gaoh").css("display","none")	
			$(".cj").css("display","none")
			$(".gk").css("display","none")
		})
		$(".a4").mouseover(function(){
			$(".h5").css("display","block")
			$(".chongci").css("display","block")
			$(".h2").css("display","none")
			$(".xiaoxue").css("display","none")
			$(".h3").css("display","none")
			$(".chuzhong").css("display","none")
			$(".h4").css("display","none")
			$(".gaozhong").css("display","none")
			$(".shu").css("display","none")
			$(".shuxue").css("display","none")
			$(".ying").css("display","none")
			$(".wuli").css("display","none")
			$(".yingyu").css("display","none")
			$(".hua").css("display","none")
			$(".gu").css("display","none")
			$(".gaoy").css("display","none")
			$(".gaow").css("display","none")
			$(".gaoh").css("display","none")	
			$(".cj").css("display","none")
			$(".gk").css("display","none")
		});
		$(".x1").mouseover(function(){
			$(".h2").css("display","block")
			$(".xiaoxue").css("display","block")
				$(".shuxue").css("display","none")
				$(".shu").css("display","none")
				$(".yingyu").css("display","none")
				$(".ying").css("display","none")
				$(".hua").css("display","none")
				$(".gu").css("display","none")
				
		})
		$(".x2").mouseover(function(){
			
			$(".h2").css("display","block")
			$(".shuxue").css("display","block")
			$(".xiaoxue").css("display","none")
			$(".shu").css("display","none")
			$(".yingyu").css("display","none")
			$(".hua").css("display","none")
			$(".gu").css("display","none")
		})
		$(".x3").mouseover(function(){
			$(".h2").css("display","block")
			$(".yingyu").css("display","block")
			$(".shuxue").css("display","none")
			$(".shu").css("display","none")
			$(".xiaoxue").css("display","none")
			$(".hua").css("display","none")
			$(".gu").css("display","none")
		})
		$(".y1").mouseover(function(){
				$(".chuzhong").css("display","block")
				$(".shu").css("display","none")
				$(".ying").css("display","none")
				$(".wuli").css("display","none")
				$(".hua").css("display","none")	
				$(".gu").css("display","none")
		})
		$(".y2").mouseover(function(){
				$(".chuzhong").css("display","none")
				$(".shu").css("display","block")
				$(".shuxue").css("display","none")
				$(".xiaoxue").css("display","none")
				$(".ying").css("display","none")
				$(".wuli").css("display","none")
				$(".hua").css("display","none")
				$(".gu").css("display","none")
		})
			$(".y3").mouseover(function(){
				$(".chuzhong").css("display","none")
				$(".ying").css("display","block")
				$(".shuxue").css("display","none")
				$(".xiaoxue").css("display","none")
				$(".shu").css("display","none")
				$(".xiaoxue").css("display","none")
				$(".gaozhong").css("display","none")
				$(".yingyu").css("display","none")
				$(".wuli").css("display","none")
				$(".hua").css("display","none")
				$(".gu").css("display","none")
		})
			$(".y4").mouseover(function(){
				$(".wuli").css("display","block")
				$(".chuzhong").css("display","none")
				$(".ying").css("display","none")
				$(".shuxue").css("display","none")
				$(".xiaoxue").css("display","none")
				$(".shu").css("display","none")
				$(".xiaoxue").css("display","none")
				$(".gaozhong").css("display","none")
				$(".yingyu").css("display","none")
				$(".hua").css("display","none")
				$(".gu").css("display","none")
				
		})
			$(".y5").mouseover(function(){
				$(".hua").css("display","block")
				$(".wuli").css("display","none")
				$(".chuzhong").css("display","none")
				$(".ying").css("display","none")
				$(".shuxue").css("display","none")
				$(".xiaoxue").css("display","none")
				$(".shu").css("display","none")
				$(".xiaoxue").css("display","none")
				$(".gaozhong").css("display","none")
				$(".yingyu").css("display","none")
				$(".gu").css("display","none")
		})
			$(".q1").mouseover(function(){
				$(".gaozhong").css("display","block")
				$(".shu").css("display","none")
				$(".ying").css("display","none")
				$(".wuli").css("display","none")
				$(".hua").css("display","none")	
				$(".gu").css("display","none")
				$(".gaoy").css("display","none")
				$(".gaow").css("display","none")
				$(".gaoh").css("display","none")	
				
		})
			$(".q2").mouseover(function(){
				$(".gu").css("display","block")
				$(".gaozhong").css("display","none")
				$(".shu").css("display","none")
				$(".gaoy").css("display","none")
				$(".gaow").css("display","none")
				$(".gaoh").css("display","none")	
				
		})
			$(".q3").mouseover(function(){
				$(".gaoy").css("display","block")
				$(".gu").css("display","none")
				$(".gaozhong").css("display","none")
				$(".gaow").css("display","none")
				$(".gaoh").css("display","none")	
		});
			$(".q4").mouseover(function(){
				$(".gaow").css("display","block")
				$(".gaoy").css("display","none")
				$(".gu").css("display","none")
				$(".gaozhong").css("display","none")
				$(".gaoh").css("display","none")	
		});
			$(".q5").mouseover(function(){
				$(".gaoh").css("display","block")
				$(".gaow").css("display","none")
				$(".gaoy").css("display","none")
				$(".gu").css("display","none")
				$(".gaozhong").css("display","none")
		});
			$(".c1").mouseover(function(){
				$(".chongci").css("display","block")
				$(".cj").css("display","none")
				$(".gk").css("display","none")
			});
			$(".c2").mouseover(function(){
				$(".cj").css("display","block")
				$(".chongci").css("display","none")
				$(".gk").css("display","none")
			});
			$(".c3").mouseover(function(){
				$(".gk").css("display","block")
				$(".cj").css("display","none")
				$(".chongci").css("display","none")
			}); 

		$(".hao").click(function(){
			showModel();
			$(window).resize(function(){
				showModel();
			});
		});
		function showModel(){
			$(".mtk-all,.mask").fadeIn();
			$("#close_freeorder").fadeIn();
			var vW=$(window).width();
			var vH=$(window).height();
			var mW=$(".mtk-all").outerWidth();
			var mH=$(".mtk-all").outerHeight();
		}
		$("#close_freeorder").click(function(){
			$(".mtk-all,.mask").fadeOut();
			});
});